import {useState} from 'react'
import {useNavigate} from 'react-router-dom'
import './Checkout.css'
export default function Checkout({cart,setCart}){
 const nav=useNavigate();const [customer,setCustomer]=useState({name:'',phone:'',address:'',payment:'Cash on Delivery'})
 const total=cart.reduce((s,x)=>s+x.price*x.quantity,0)
 const submit=e=>{e.preventDefault();if(!cart.length)return alert('Your cart is empty!');if(!customer.name||!customer.phone||!customer.address)return alert('Please fill all delivery details.')
 const order={orderId:'FM'+Date.now(),customer,items:cart,total,status:'Order Placed',date:new Date().toLocaleDateString()}
 localStorage.setItem('freshmartOrders',JSON.stringify([...(JSON.parse(localStorage.getItem('freshmartOrders'))||[]),order]));setCart([]);nav('/order-success',{state:{order}})}
 return <main className="checkout-page"><h1>Checkout</h1><div className="checkout-container"><form className="checkout-form" onSubmit={submit}><h2>Delivery Details</h2><label>Full Name<input value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>Mobile Number<input value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>Delivery Address<textarea value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></label><label>Payment Method<select value={customer.payment} onChange={e=>setCustomer({...customer,payment:e.target.value})}><option>Cash on Delivery</option><option>UPI</option><option>Card</option></select></label><button className="place-order-button">Place Order</button></form><aside className="order-summary"><h2>Order Summary</h2>{cart.map(x=><div className="summary-item" key={x.id}><span>{x.name} × {x.quantity}</span><span>₹{x.price*x.quantity}</span></div>)}<div className="summary-total"><span>Total</span><strong>₹{total}</strong></div></aside></div></main>}