import {useState} from 'react'
import {BrowserRouter,Routes,Route,useLocation} from 'react-router-dom'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import Home from './pages/Home'
import Products from './pages/Products'
import Cart from './pages/Cart'
import Checkout from './pages/Checkout'
import OrderSuccess from './pages/OrderSuccess'
import Login from './pages/Login'
import AdminLogin from './admin/AdminLogin'
import AdminLayout from './admin/AdminLayout'
import AdminDashboard from './admin/AdminDashboard'
import ManageProducts from './admin/ManageProducts'
import ManageCategories from './admin/ManageCategories'
import ManageUsers from './admin/ManageUsers'
import ManageOrders from './admin/ManageOrders'
import ManagePayments from './admin/ManagePayments'
import AddProduct from './admin/AddProduct'
import './App.css'
function Content(){const [cart,setCart]=useState([]);const location=useLocation();const isAdmin=location.pathname.startsWith('/admin');const addToCart=(product)=>setCart(c=>{const found=c.find(x=>x.id===product.id);return found?c.map(x=>x.id===product.id?{...x,quantity:x.quantity+1}:x):[...c,{...product,quantity:1}]});return <><>{!isAdmin&&<Navbar cart={cart}/>}</><Routes><Route path="/" element={<Home setCart={addToCart}/>}/><Route path="/products" element={<Products setCart={addToCart}/>}/><Route path="/cart" element={<Cart cart={cart} setCart={setCart}/>}/><Route path="/checkout" element={<Checkout cart={cart} setCart={setCart}/>}/><Route path="/order-success" element={<OrderSuccess/>}/><Route path="/login" element={<Login/>}/><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin" element={<AdminLayout/>}><Route path="dashboard" element={<AdminDashboard/>}/><Route path="products" element={<ManageProducts/>}/><Route path="products/add" element={<AddProduct/>}/><Route path="categories" element={<ManageCategories/>}/><Route path="users" element={<ManageUsers/>}/><Route path="orders" element={<ManageOrders/>}/><Route path="payments" element={<ManagePayments/>}/></Route></Routes>{!isAdmin&&<Footer/>}</>}
export default function App(){return <BrowserRouter><Content/></BrowserRouter>}